/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  type AbiType,
  AztecAddress,
  type AztecAddressLike,
  CompleteAddress,
  Contract,
  type ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  type ContractInstanceWithAddress,
  type ContractMethod,
  type ContractStorageLayout,
  type ContractNotes,
  decodeFromAbi,
  DeployMethod,
  EthAddress,
  type EthAddressLike,
  EventSelector,
  type FieldLike,
  Fr,
  type FunctionSelectorLike,
  L1EventPayload,
  loadContractArtifact,
  type NoirCompiledContract,
  NoteSelector,
  Point,
  type PublicKey,
  type UnencryptedL2Log,
  type Wallet,
  type WrappedFieldLike,
} from "@aztec/aztec.js";
import AccountGroupContractArtifactJson from "../../target/account_group-AccountGroup.json" assert { type: "json" };
export const AccountGroupContractArtifact = loadContractArtifact(
  AccountGroupContractArtifactJson as unknown as NoirCompiledContract
);

/**
 * Type-safe interface for contract AccountGroup;
 */
export class AccountGroupContract extends ContractBase {
  private constructor(instance: ContractInstanceWithAddress, wallet: Wallet) {
    super(instance, AccountGroupContractArtifact, wallet);
  }

  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(address: AztecAddress, wallet: Wallet) {
    return Contract.at(
      address,
      AccountGroupContract.artifact,
      wallet
    ) as Promise<AccountGroupContract>;
  }

  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(
    wallet: Wallet,
    signing_pub_key_x: FieldLike,
    signing_pub_key_y: FieldLike,
    admin: AztecAddressLike
  ) {
    return new DeployMethod<AccountGroupContract>(
      Fr.ZERO,
      wallet,
      AccountGroupContractArtifact,
      AccountGroupContract.at,
      Array.from(arguments).slice(1)
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeysHash(
    publicKeysHash: Fr,
    wallet: Wallet,
    signing_pub_key_x: FieldLike,
    signing_pub_key_y: FieldLike,
    admin: AztecAddressLike
  ) {
    return new DeployMethod<AccountGroupContract>(
      publicKeysHash,
      wallet,
      AccountGroupContractArtifact,
      AccountGroupContract.at,
      Array.from(arguments).slice(2)
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof AccountGroupContract["methods"]>(
    opts: { publicKeysHash?: Fr; method?: M; wallet: Wallet },
    ...args: Parameters<AccountGroupContract["methods"][M]>
  ) {
    return new DeployMethod<AccountGroupContract>(
      opts.publicKeysHash ?? Fr.ZERO,
      opts.wallet,
      AccountGroupContractArtifact,
      AccountGroupContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? "constructor"
    );
  }

  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return AccountGroupContractArtifact;
  }

  public static get storage(): ContractStorageLayout<
    "signing_public_key" | "admin" | "group_members" | "member_balances"
  > {
    return {
      signing_public_key: {
        slot: new Fr(1n),
      },
      admin: {
        slot: new Fr(2n),
      },
      group_members: {
        slot: new Fr(3n),
      },
      member_balances: {
        slot: new Fr(4n),
      },
    } as ContractStorageLayout<
      "signing_public_key" | "admin" | "group_members" | "member_balances"
    >;
  }

  public static get notes(): ContractNotes<
    | "ValueNote"
    | "TokenNote"
    | "AddressNote"
    | "TransparentNote"
    | "PublicKeyNote"
    | "NewAddressNote"
  > {
    return {
      ValueNote: {
        id: new NoteSelector(1038582377),
      },
      TokenNote: {
        id: new NoteSelector(2350566847),
      },
      AddressNote: {
        id: new NoteSelector(2232136525),
      },
      TransparentNote: {
        id: new NoteSelector(3193649735),
      },
      PublicKeyNote: {
        id: new NoteSelector(2806681024),
      },
      NewAddressNote: {
        id: new NoteSelector(4235158996),
      },
    } as ContractNotes<
      | "ValueNote"
      | "TokenNote"
      | "AddressNote"
      | "TransparentNote"
      | "PublicKeyNote"
      | "NewAddressNote"
    >;
  }

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    /** add_member(member: struct) */
    add_member: ((member: AztecAddressLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** compute_note_hash_and_optionally_a_nullifier(contract_address: struct, nonce: field, storage_slot: field, note_type_id: field, compute_nullifier: boolean, serialized_note: array) */
    compute_note_hash_and_optionally_a_nullifier: ((
      contract_address: AztecAddressLike,
      nonce: FieldLike,
      storage_slot: FieldLike,
      note_type_id: FieldLike,
      compute_nullifier: boolean,
      serialized_note: FieldLike[]
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** constructor(signing_pub_key_x: field, signing_pub_key_y: field, admin: struct) */
    constructor: ((
      signing_pub_key_x: FieldLike,
      signing_pub_key_y: FieldLike,
      admin: AztecAddressLike
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** entrypoint() */
    entrypoint: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_admin() */
    get_admin: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_balance(creditor: struct, debtor: struct) */
    get_balance: ((
      creditor: AztecAddressLike,
      debtor: AztecAddressLike
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** make_payment(debtor: struct, creditor: struct, amount: field) */
    make_payment: ((
      debtor: AztecAddressLike,
      creditor: AztecAddressLike,
      amount: FieldLike
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** set_balance(creditor: struct, debtor: struct, amount: field) */
    set_balance: ((
      creditor: AztecAddressLike,
      debtor: AztecAddressLike,
      amount: FieldLike
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** setup_group_payments(creditor: struct, debtors: array, amount: field) */
    setup_group_payments: ((
      creditor: AztecAddressLike,
      debtors: AztecAddressLike[],
      amount: FieldLike
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** view_member(position: integer) */
    view_member: ((position: bigint | number) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;
  };
}
